from pathlib import Path
data_path = Path('data/')
# case_id = 9
case_id = 14
out_path = data_path / f'case_{case_id}'
# ref, ab, ag = "4G6M_HL:A", "4G6K_HL", "4I1B_A"
ref, ab, ag = "3L5W_LH:I", "3L7E_LH", "1IK0_A(11)"
ab_pdb_src = str(data_path / '0_base' / f'{ab[:4]}.pdb')
prep_dir = out_path / '1_pre'
ab_pdb_clean = str(prep_dir / f'{ab[:4]}_clean_ab.pdb')
ag_pdb_clean = str(prep_dir / f'{ag[:4]}_clean_ag.pdb')
ref_pdb_clean = str(prep_dir / f'{ref[:4]}_clean_ref.pdb')
ref_interface = str(prep_dir / f'{ref[:4]}_interface.txt')
ab_actpass = str(prep_dir / f'{ab[:4]}_actpass.txt')
complex_tbl = str(prep_dir / f'{ag[:4]}_ambig.tbl')
body_tbl = str(prep_dir / f'{ag[:4]}_unambig.tbl')
dock_dir = out_path / '2_dock'
# MD
MD_dir = out_path / '3_MD'
ab_pdb_src_ch = str(prep_dir / 'chains_ab.pdb')
fixed_pdb = str(MD_dir / f'{ab}_fixed.pdb')
output_pdb2gmx_gro = str(MD_dir / f'{ab}_pdb2gmx.gro')
output_pdb2gmx_top_zip = str(MD_dir / f'{ab}_pdb2gmx_top.zip')
output_editconf_gro = str(MD_dir / f'{ab}_editconf.gro')
output_solvate_gro = str(MD_dir / f'{ab}_solvate.gro')
output_solvate_top_zip = str(MD_dir / f'{ab}_solvate_top.zip')
input_mdp_min = MD_dir / "emin-charmm.mdp"
input_mdp_eq = MD_dir / "md_eq_posre_charmm36m.mdp"
output_gppmin_tpr = MD_dir / f'{ab}_gppmin.tpr'
output_md_trr = MD_dir / f'{ab}_md.trr'
output_md_gro = MD_dir / f'{ab}_md.gro'
output_md_edr = MD_dir / f'{ab}_md.edr'
output_md_log = MD_dir / f'{ab}_md.log'
output_md_cpt = MD_dir / f'{ab}_md.cpt'
output_imaged_traj = MD_dir / f'{ab}_imaged_traj.trr'
output_imaged_traj_rot = MD_dir / f'{ab}_imaged_traj_rot.trr'
anarcii_pdb = str(Path(fixed_pdb).with_name(f'{ab}_anarcii_imgt.pdb'))
loop_ndx = MD_dir / f'{ab}_loop.ndx'
MD_pdb_cluster = MD_dir / f'{ab}_clusters.pdb'
MD_pdb_cluster_clean = str(MD_dir / f'{ab}_clusters_clean.pdb')
MD_dock_dir = MD_dir / 'docking'
# AWH
AWH_dir = out_path / '4_AWH'
AWH_fixed_pdb = str(AWH_dir / f'{ref}_fixed.pdb')
AWH_input_ndx = str(AWH_dir / "index.ndx")
AWH_output_pdb2gmx_gro = str(AWH_dir / f'{ref}_pdb2gmx.gro')
AWH_output_pdb2gmx_top_zip = str(AWH_dir / f'{ref}_pdb2gmx_top.zip')
AWH_output_editconf_gro = str(AWH_dir / f'{ref}_editconf.gro')
AWH_output_solvate_gro = str(AWH_dir / f'{ref}_solvate.gro')
AWH_output_solvate_top_zip = str(AWH_dir / f'{ref}_solvate_top.zip')
AWH_output_genion_gro = str(AWH_dir / f'{ref}_genion.gro')
AWH_output_genion_top_zip = str(AWH_dir / f'{ref}_genion_top.zip')
AWH_output_gppmin_tpr = AWH_dir / f'{ref}_gppmin.tpr'
AWH_output_min_trr = AWH_dir / f'{ref}_min.trr'
AWH_output_min_gro = AWH_dir / f'{ref}_min.gro'
AWH_output_min_edr = AWH_dir / f'{ref}_min.edr'
AWH_output_min_log = AWH_dir / f'{ref}_min.log'
AWH_output_min_ene_xvg = AWH_dir / f'{ref}_min_ene.xvg'
AWH_output_nvt_tpr = AWH_dir / f'{ref}_nvt.tpr'
AWH_output_nvt_trr = AWH_dir / f'{ref}_nvt.trr'
AWH_output_nvt_gro = AWH_dir / f'{ref}_nvt.gro'
AWH_output_nvt_edr = AWH_dir / f'{ref}_nvt.edr'
AWH_output_nvt_log = AWH_dir / f'{ref}_nvt.log'
AWH_output_nvt_cpt = AWH_dir / f'{ref}_nvt.cpt'
AWH_output_nvt_temp_xvg = AWH_dir / f'{ref}_nvt_temp.xvg'
AWH_output_gppnpt_tpr = AWH_dir / f'{ref}_gppnpt.tpr'
AWH_output_npt_trr = AWH_dir / f'{ref}_npt.trr'
AWH_output_npt_gro = AWH_dir / f'{ref}_npt.gro'
AWH_output_npt_edr = AWH_dir / f'{ref}_npt.edr'
AWH_output_npt_log = AWH_dir / f'{ref}_npt.log'
AWH_output_npt_cpt = AWH_dir / f'{ref}_npt.cpt'
AWH_output_gppmd_tpr = AWH_dir / f"{ref}_gppmd.tpr"
input_mdp_awh = AWH_dir / "awh_md.mdp"
AWH_output_md_trr = AWH_dir / f'{ref}_md.trr'
AWH_output_md_gro = AWH_dir / f'{ref}_md.gro'
AWH_output_md_edr = AWH_dir / f'{ref}_md.edr'
AWH_output_md_log = AWH_dir / f'{ref}_md.log'
AWH_output_md_cpt = AWH_dir / f'{ref}_md.cpt'
input_mdp_awh_mult = AWH_dir / "awh_md_mult.mdp"
walker_dir = AWH_dir / 'walkers' / "walker_1"
AWH_output_gppmd_mult_tpr = walker_dir / f"{ref}_gppmd_mult.tpr"
AWH_trjcat_path = AWH_dir / f'{ref}_md_awh_cat.xtc'
AWH_imaged_traj = AWH_dir / f'{ab}_imaged_traj.trr'
AWH_dry_gro = AWH_dir / f'{ab}_md_dry.gro'
AWH_imaged_traj_rot = AWH_dir / f'{ab}_imaged_traj_rot.trr'
AWH_pdb_cluster = AWH_dir / f'{ab}_clusters.pdb'
AWH_pdb_cluster_clean = str(AWH_dir / f'{ab}_clusters_clean.pdb')